// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdmTMH1EfpKhDzqNS7VObhPeXc_5nk19k',
    appId: '1:230854304462:web:cb0ec49a7e46f11e92669f',
    messagingSenderId: '230854304462',
    projectId: 'fyp-proj-df4a5',
    authDomain: 'fyp-proj-df4a5.firebaseapp.com',
    storageBucket: 'fyp-proj-df4a5.appspot.com',
    measurementId: 'G-BYR5CLF4BF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmJd8F0RSVhTBxB_KOUvRWRgXvgQQ8jVU',
    appId: '1:230854304462:android:32055ae61a50134192669f',
    messagingSenderId: '230854304462',
    projectId: 'fyp-proj-df4a5',
    storageBucket: 'fyp-proj-df4a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6gcICmoVEi3MeIRiarnV_HLEA4s-qSE0',
    appId: '1:230854304462:ios:7335eb671ec54c8092669f',
    messagingSenderId: '230854304462',
    projectId: 'fyp-proj-df4a5',
    storageBucket: 'fyp-proj-df4a5.appspot.com',
    iosClientId: '230854304462-a37j4pbc3ojsc74p52s73rbn7d88mgnq.apps.googleusercontent.com',
    iosBundleId: 'com.example.medApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6gcICmoVEi3MeIRiarnV_HLEA4s-qSE0',
    appId: '1:230854304462:ios:7335eb671ec54c8092669f',
    messagingSenderId: '230854304462',
    projectId: 'fyp-proj-df4a5',
    storageBucket: 'fyp-proj-df4a5.appspot.com',
    iosClientId: '230854304462-a37j4pbc3ojsc74p52s73rbn7d88mgnq.apps.googleusercontent.com',
    iosBundleId: 'com.example.medApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdmTMH1EfpKhDzqNS7VObhPeXc_5nk19k',
    appId: '1:230854304462:web:398719f90364541c92669f',
    messagingSenderId: '230854304462',
    projectId: 'fyp-proj-df4a5',
    authDomain: 'fyp-proj-df4a5.firebaseapp.com',
    storageBucket: 'fyp-proj-df4a5.appspot.com',
    measurementId: 'G-6WPV2R0MRD',
  );

}